elixir-webrtc/ex_webrtc

examples/example.exs
lib/ex_webrtc/media_stream_track.ex
lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/peer_connection/configuration.ex
lib/ex_webrtc/rtp_transceiver.ex
lib/ex_webrtc/utils.ex
test/peer_connection_test.exs

Definitely not perfect and for sure bugged but maybe this can be a base for further work.
The idea is that we iterate over mlines in SDP, we try to find a transceiver for a given mline, if it exists we potentially update its configuraiton. If it doesn't exist we create a new one. At the end we compare previous transceivers with new transceivers and try to find new MediaStreamTracks

Create transceivers on set_remote_description

---

examples/example.exs
lib/ex_webrtc/dtls_transport.ex
lib/ex_webrtc/peer_connection.ex

Additionally, fixes some bugs with active mode.

Move DTLS utilities to `DTLSTransport` module

---

.github/workflows/ci.yml
codecov.yml

* disabled github notifications that something is not covered by tests
* we don't need to wait for other checks to run codecov
* changed the layout of codecov comment so we see more info. Behavior `default` means that the comment is updated when new commits appear
* disabled coverage threshold

Configure codecov

---

lib/ex_webrtc/peer_connection.ex

The benefit of Structs over maps is that we have compile time checks so e.g. if we do `state.non_existing_field` we will be warned by the compiler about this fact.
If we want to keep structs for internal states, we should also convert DTLSTransport state into struct.
Any thoughts?
Personally, I would move to maps :stuck_out_tongue:

Convert PeerConnection internal state into map

---

lib/ex_webrtc/peer_connection/configuration.ex
lib/ex_webrtc/rtp_codec_parameters.ex
test/ex_webrtc/peer_connection/configuration_test.exs

see https://github.com/elixir-webrtc/ex_webrtc/issues/28#issuecomment-1845862824

Add AV1 to the list of default video codecs

---

examples/echo/example.exs
lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/rtp_sender.ex
lib/ex_webrtc/rtp_transceiver.ex
test/ex_webrtc/peer_connection_test.exs

Additionally, I made the `echo` example to use `add_track/2`.

Add `add_track/2` function to API

---

examples/send_from_file/example.exs
lib/ex_webrtc/rtp/opus_payloader.ex

More for the sake of consistency, as it basically does not do anything.

Add Opus payloader

---

examples/send_from_file/example.exs
lib/ex_webrtc/media/ogg/header.ex
lib/ex_webrtc/media/ogg/page.ex
lib/ex_webrtc/media/ogg_reader.ex
lib/ex_webrtc/media/ogg_writer.ex
lib/ex_webrtc/media/opus.ex
test/ex_webrtc/media/ogg/page_test.exs
test/ex_webrtc/media/ogg_reader_test.exs
test/ex_webrtc/media/ogg_writer_test.exs

Adds the `OggWriter` and its tests.
Example will be updated in the following Pull Request.

Ogg writer

---

examples/save_to_file/.gitignore
examples/save_to_file/README.md
examples/save_to_file/example.exs
examples/save_to_file/example.html
examples/save_to_file/example.js
examples/send_from_file/example.exs
lib/ex_webrtc/rtp/opus_depayloader.ex

- adds Ogg `save_to_file` example,
- makes variable naming in examples consistent,
- adds Opus depayloader (for the sake of consistency)

Extend Ogg examples

---

examples/echo/example.exs
examples/save_to_file/example.exs
examples/save_to_file/example.html
examples/send_from_file/example.exs
lib/ex_webrtc/dtls_transport.ex

When we notice ExDTLS error, DTLSTransport will stop itself and because it is linked with PeerConnection and PeerConnection is linked with ICETransport, everything will stop too

Handle ExDTLS errors

---

lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/rtp_sender.ex
lib/ex_webrtc/rtp_transceiver.ex
test/ex_webrtc/peer_connection_test.exs

New m-line in a remote offer always resulted in our `PeerConnection` creating new transceiver, when it should firstly look for a transceiver that is "associable" (see RFC 8829, sec. 5.10).
This PR fixes the issue.

Fix bug with choosing transceiver for remote m-line

---

lib/ex_webrtc/peer_connection.ex

Looks like Firefox won't start sending data until there is at least one nominated pair.
Even when it has succeeded pair.
I ran FF with `MOZ_LOG=webrtc_trace:5 firefox` and in `about:firefox` there is:
```
ICE-PEER(PC:{c24206e8-75db-4355-a73b-de9a9828c09c} 1707254636988657 (id=6442450946 url=http://127.0.0.1:8829/index.html):default)/CAND-PAIR(kWR0): setting pair to state SUCCEEDED: ...
```
In our ICE implementation, we only nominate after the remote side has indicated that there won't be any new remote candidates - we follow RFC 8445.
IIRC, most of implementations rely on aggressive nomination described in RFC 5245.
Our implementation should be compatible both with 8445 and 5245 but apparently I might have missed something.
Calling end_of_candidates solves the problem but this needs …

Call end_of_candidates on receiving an empty ICE candidate

---

lib/ex_webrtc/peer_connection.ex

hey, in my experimentation, this handle_cast for `:send_rtp` always receives a full track, not an id. This change makes everything work, but if you want it to be different feel free to edit my pr.

Allow `MediaStreamTrack.t()` as a parameter to `send_rtp/3` 

---

lib/ex_webrtc/peer_connection.ex

Fixes bug merged in #63, where values returned from `TWCCRecorder.get_feedback/1` are assigned to invalid variables.

Fix invalid order of return values from `TWCCRecorder.get_feedback/1

---

examples/echo/lib/echo/peer_handler.ex

Wanted to contribute an example like the one in the Pion project here: https://github.com/pion/webrtc/tree/master/examples/rtcp-processing

adding rtcp processing example

---

guides/mastering_transceivers.md

The `track` notification may be triggered both when setting a remote offer and a remote answer. I've updated the example to explicitly demonstrate this case.

Update bidirectional connection example in the transceiver guide

---

lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/peer_connection/twcc_recorder.ex
test/ex_webrtc/peer_connection/twcc_recorder_test.exs

The `TWCCRecorder` module has a default argument that keeps the initial value of `System.monotonic_time()` (so the subsequent calls could be offset to be positive, as output of `System.monotonic_time()` is usually negative). The value is evaluated at the compile time and differs from the runtime base `System.monotonic_time()` value, which is obviously undesired. This PR fixes this issue.

Fix `TWCCRecorder` base timestamp evaluation bug

---

lib/ex_webrtc/peer_connection/configuration.ex

Now, on `set_remote_description`, our PeerConnection's config is updated with RTP header extension IDs from the remote offer/answer. This PR fixes the issue of only updating either audio or video extensions, not both at the same time, which is a bug.

Fix issue with not-updating RTP header extensions on remote description

---

.github/workflows/ci.yml
.gitignore
lib/ex_webrtc/media/ivf/writer.ex
lib/ex_webrtc/peer_connection.ex
mix.exs
test/test_helper.exs

This PR:
- adds caching of `deps`, `_build` and `dialyzer` artifacts,
- updates some of the actions versions (and thus removes warnings),
- consolidates everything into a single GH Workflow job (both of previous jobs required compilation and now it's very fast anyways).
Thanks to this the CI should be much, much faster.
Based on https://fly.io/docs/elixir/advanced-guides/github-actions-elixir-ci-cd/ and https://www.alanvardy.com/post/caching-dialyzer with some tweaks here and there.

Improve CI

---

lib/ex_webrtc/dtls_transport.ex
lib/ex_webrtc/peer_connection.ex
test/ex_webrtc/dtls_transport_test.exs

This PR makes it possible to receive data (e.g. DTLS handshake packets) from the remote peer before receiving an answer.
Now:
1. Our ICE implementation allows data from unauthorised peer (so before we receive their credentials in an answer),
2. DTLS requires remote's certs to perform the handshake.
`DTLSTransport` will now buffer packets received before receiving an answer and handle them after the transport has been initialised (so after answer has been set).

Handle incoming data before receiving an answer

---

lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/rtp_receiver.ex
lib/ex_webrtc/rtp_receiver/nack_generator.ex
lib/ex_webrtc/rtp_receiver/report_recorder.ex
lib/ex_webrtc/rtp_sender.ex
lib/ex_webrtc/rtp_sender/nack_responder.ex
lib/ex_webrtc/rtp_sender/report_recorder.ex
lib/ex_webrtc/rtp_transceiver.ex

This PR:
- removes most of the stuff that should be private from `RTPTransceiver`, `RTPSender` and `RTPReceiver` structs (like the "recorder..." modules)
- adds some getters to the `PeerConnection` (for the various states)
- adds doc stubs to most of the function in the API in general

Improve the structs in the API, add docs

---

lib/ex_webrtc/peer_connection.ex
test/ex_webrtc/peer_connection_test.exs

I did not returned a `{:stop, :unrecognized_id, state}` as I don't know how you want to treat this.

Fix send_rtp for non-existing track id

---

lib/ex_webrtc/rtp/opus/depayloader.ex
lib/ex_webrtc/rtp/opus/payloader.ex
lib/ex_webrtc/rtp/vp8/depayloader.ex
lib/ex_webrtc/rtp/vp8/payload.ex
lib/ex_webrtc/rtp/vp8/payloader.ex
test/ex_webrtc/rtp/vp8/depayloader_test.exs
test/ex_webrtc/rtp/vp8/payload_test.exs
test/ex_webrtc/rtp/vp8/payloader_test.exs

In `ExWebRTC.RTP.*`, instead of using `CodecPayloder`, we now use the convention of `Codec.Payloader`, similar to how it is done in `ExWebRTC.Media.*`. This will be convenient in my next PR (where I'm going to add an `RTP.Munger` and `keyframe?` function for particular codecs).

Create a module for every codec in `ExWebRTC.RTP`

---

lib/ex_webrtc/peer_connection/configuration.ex

As we don't compare FMTP in `intersect_codecs`, we can safely remove its specification from default codecs

Remove redundant FMTP specification from default codecs

---

examples/echo/lib/echo/peer_handler.ex
examples/whip_whep/lib/whip_whep/forwarder.ex
lib/ex_webrtc/peer_connection.ex
test/ex_webrtc/peer_connection_test.exs

Add `track_id` to packets sent in `{:rtcp, ...}` message

---

lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/sdp_utils.ex
test/ex_webrtc/peer_connection_test.exs

Fixes:
- `set_remote_description` won't try to use ICE credentials from rejected m-lines (and subsequently, won't fail if ICE credentials in rejected m-lines differ from credentials in active m-lines),
- `set_remote_description` won't fail when all of the m-lines are rejected (so there's no valid ICE credentials in the description). In such case, it will either not connect (for the first description) or use credentials from previous descriptions (for the subsequent descriptions)
Other elements of rejected m-lines might need to be ignored as well (like MIDs, fingerprints, etc.), but it seems like browsers include them anyway, so for now this fix seems to be enough.
Close #144

Fix `set_remote_description` failing on description with rejected m-lines

---

lib/ex_webrtc/dtls_transport.ex

Closes #137
This isn't really a fix per se, but at least DTLSTransport won't crash anymore

Handle other retransmit case in DTLSTransport

---

examples/send_from_file/lib/send_from_file/peer_handler.ex
lib/ex_webrtc/rtp/depayloader.ex
lib/ex_webrtc/rtp/depayloader_behaviour.ex
lib/ex_webrtc/rtp/opus/depayloader.ex
lib/ex_webrtc/rtp/opus/payloader.ex
lib/ex_webrtc/rtp/payloader.ex
lib/ex_webrtc/rtp/payloader_behaviour.ex
lib/ex_webrtc/rtp/vp8/depayloader.ex
lib/ex_webrtc/rtp/vp8/payload.ex
lib/ex_webrtc/rtp/vp8/payloader.ex
test/ex_webrtc/rtp/depayloader_test.exs
test/ex_webrtc/rtp/payloader_test.exs
test/ex_webrtc/rtp/vp8/depayloader_test.exs
test/ex_webrtc/rtp/vp8/payloader_test.exs

Sorry, I don't want to mess in your PR but I have a couple of observations:
* depayloaders does not take any options right now so we can get rid of them
* all payloaders can take the same argument - max_payload_size
* if the two above are true, we can hide everything except `ExWebRTC.RTP.Payloader` and `ExWebRTC.RTP.Depayloader` - user doesn't have to know about specific payloader/depayloader modules
* we can extract payloader/depayloader behaviours into separate modules so they are private too. If we want to provide automatic dispatching, user won't be able to implement those behaviours as our dispatcher's `new` function has to be modified anyway
An alternative approach would be to use Protocols. The API would look like this:
```elixir
defprotocol ExWebRTC.RTP.Payloader do
def …
```

Hide VP8 and Opus Payloader/Depayloader modules

---

examples/save_to_file/lib/save_to_file/peer_handler.ex
examples/send_from_file/lib/send_from_file/peer_handler.ex
lib/ex_webrtc/rtp/depayloader.ex
lib/ex_webrtc/rtp/depayloader_behaviour.ex
lib/ex_webrtc/rtp/opus/depayloader.ex
lib/ex_webrtc/rtp/opus/payloader.ex
lib/ex_webrtc/rtp/payloader.ex
lib/ex_webrtc/rtp/payloader_behaviour.ex
lib/ex_webrtc/rtp/vp8/depayloader.ex
lib/ex_webrtc/rtp/vp8/payload.ex
lib/ex_webrtc/rtp/vp8/payloader.ex
test/ex_webrtc/rtp/depayloader_test.exs
test/ex_webrtc/rtp/payloader_test.exs
test/ex_webrtc/rtp/vp8/depayloader_test.exs
test/ex_webrtc/rtp/vp8/payloader_test.exs

Add behaviour and dynamic dispatch for (de)payloaders

---

lib/ex_webrtc/dtls_transport.ex

This is exceedingly rare but can happen in extremely poor network conditions due to jitter -- and when it happens, it results in dropping the initial keyframe

Buffer RT(C)P packets that arrive pre-DTLS handshake completion

---

lib/ex_webrtc/ice_candidate.ex
lib/ex_webrtc/peer_connection.ex

Fix type defnitions to match the actual types

Fix ICECandidate types

---

lib/ex_webrtc/ice_candidate.ex

I ran into an error because `flutter-webrtc`(https://github.com/flutter-webrtc/webrtc-interface/blob/767eb083a9ee88a4e37b49cb70bb7831c7c2414d/lib/src/rtc_ice_candidate.dart#L6) doesn't seem to send this field.
The ICECandidate type spec already allows the field to be nil. This PR would also allow candidates where the `usernameFragment` field is not present at all.

Handle ICE candidates with missing `usernameFragment`

---

lib/ex_webrtc/dtls_transport.ex
lib/ex_webrtc/peer_connection.ex
test/ex_webrtc/dtls_transport_test.exs

This PR adds an ability to set very simple packet loss for a peer connection.
While I haven't seen such function in any other WebRTC implementation, I found it useful for experimental and demo purposes where setting packet loss on a network interface might be too broad.

Add PeerConneciton.set_packet_loss

---

lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/rtp_sender.ex
lib/ex_webrtc/rtp_sender/nack_responder.ex
lib/ex_webrtc/rtp_transceiver.ex
test/ex_webrtc/rtp_sender_test.exs
test/ex_webrtc/rtp_transceiver_test.exs

Some implementations still rely on ssrc attributes in SDP offer/answer when demuxing incoming RTP packets (e.g. Pion). While including a=ssrc attribute in the SDP is obsoleted and we should demux by mid, including ssrc is still correct and supported by web browsers.
This PR adds ssrc attributes to the SDP offer/answer when a transceiver is sendonly or sendrecv.
A couple of notes:
* in theory, if we add `a=ssrc:1234` attribute, it should also always has cname attr i.e. `a=ssrc:1234 cname:qW34eced` (RFC 5567)
* we don't use cnames so we don't do this. Instead we always add msid attribute as we already have it
* we stop sending app_data in msid according to what JSEP says (RFC 8829). This app_data does not make any sense anyway as its value is MediaStreamTrack.id, which can change without …

Add ssrc attributes to the SDP

---

test/ex_webrtc/data_channel_test.exs

`PeerConnection.send_data` is asynchronous, so before checking stats, we need to ensure that the other side received our messages.

Fix RC in data_channel_test.exs

---

lib/ex_webrtc/rtp_receiver.ex
lib/ex_webrtc/rtp_sender.ex
lib/ex_webrtc/rtp_transceiver.ex
lib/ex_webrtc/utils.ex
test/ex_webrtc/rtp_receiver_test.exs
test/ex_webrtc/rtp_sender_test.exs

This PR passes all codecs that were negotiated to the RTP sender and RTP receiver. Because in our case these codecs are always the same i.e. (transceiver.codecs==sender.codecs==receiver.codecs), they are not publicly exposed in RTPSender and RTPReceiver structs to not create confusion or suggest that they may differ. 
The behavior of RTP sender and receiver remains the same i.e. they always pick the first codec and use it for sending or expect it when receiving RTP packets.
In the next PR, I am going to allow to set codec that should be used for sending.

Pass all codecs instead of selected one to the rtp_receiver and rtp_sender

---

lib/ex_webrtc/peer_connection.ex
lib/ex_webrtc/peer_connection/configuration.ex
lib/ex_webrtc/rtp_sender.ex
lib/ex_webrtc/rtp_sender/report_recorder.ex
lib/ex_webrtc/rtp_transceiver.ex
test/ex_webrtc/peer_connection/configuration_test.exs
test/ex_webrtc/peer_connection_test.exs
test/ex_webrtc/renegotiation_test.exs
test/ex_webrtc/rtp_sender/report_recorder_test.exs
test/ex_webrtc/rtp_sender_test.exs
test/ex_webrtc/rtp_transceiver_test.exs

This PR allows to set codec that should be used for sending with the following remarks:
* when the first RTP packet is sent, the clock rate used by RTP sender is "locked" meaning that any subsequent call to the `set_sender_codec` must use a codec with the same clock rate. This is because using a new clock rate requires a new SSRC. Also, ReportRecorder, which generates RTCP reports relies on clock rate so changing it after we started sending packets could result in incorrect reports
* when a codec was selected, and as a result of renegotiation it is no longer supported, user must call `set_sender_codec` with a new codec that is supported
It also:
* moves initialization of ReportRecorder so that now, it is initialized when the first packet is sent
* adds checking FMTP parameters  when …

Add set_sender_codec

---

README.md
lib/ex_webrtc/recorder.ex
mix.exs

Fixes issue outlined in #194
The new tracks were correctly merged into `state` in line 169 but `state` was then erroneously updated again in line 180, causing the freshly added tracks to override the existing ones.

Fix recorder overriding tracks instead of merging on `add_tracks`. Release 0.8.1

---

guides/advanced/simulcast.md
lib/ex_webrtc/rtp/munger.ex
lib/ex_webrtc/rtp/vp8.ex
lib/ex_webrtc/rtp/vp8/munger.ex
test/ex_webrtc/rtp/munger_test.exs
test/ex_webrtc/rtp/vp8/munger_test.exs

This PR moves and adjusts VP8 simulcast code from [Membrane RTC Engine](https://github.com/fishjam-dev/membrane_rtc_engine/blob/master/webrtc/lib/webrtc/vp8_munger.ex)

Add support for VP8 simulcast

---

lib/ex_webrtc/peer_connection.ex
test/ex_webrtc/data_channel_test.exs

- Added a parameter to the `PeerConnection.send_data` function to allow for the choice between `:binary` and `:string`.
- Added a simple test to verify the new `PeerConnection.send_data/4` arity.
No tests were added to validate the correctness of the payload, as it's handled by [ex_sctp](https://github.com/elixir-webrtc/ex_sctp) and would require some sort of passthrough mock. Please let me know if this would require testing and what the preferred approach would be.

feat: Add `data_type` configuration to `PeerConnection.send_data`

---

lib/ex_webrtc/sctp_transport.ex
lib/ex_webrtc/sctp_transport/dcep.ex

Pion seems to pad DataChannelAck to 4 bytes: https://github.com/pion/datachannel/blob/master/message_channel_ack.go#L10

Accept padded DataChannelAck, fix closing DataChannel

---

lib/ex_webrtc/sdp_utils.ex

fix get ice lite not recognized sdp offer that has "a=ice-lite"

get ice-lite returning nil
